branches:
  only:
  - kheops-master
  
sudo: required

services:
  - docker
  
notifications:
  email: false
    
script:
  - export BRANCH=$TRAVIS_BRANCH
  - chmod +x docker/docker_push.sh
  - ./docker/docker_push.sh
