language: node_js

node_js:
  - "lts/*"

services:
  - docker

notifications:
  email: false

before_script:
  - export PATH=$HOME/.meteor:$PATH

#cache:
#  directories:
#    - ~/.meteor
#    - node_modules
#    - OHIFViewer/node_modules

before_script:
  - export METEOR_PACKAGE_DIRS="../../Packages"
  - cd StandaloneViewer
  - mkdir buildDirectory
  - cd StandaloneViewer
  - npm install -g meteor-build-client-fixed@0.4.3
  - meteor-build-client-fixed --version
  - curl https://install.meteor.com | /bin/sh
  - meteor npm install
script:
  - meteor-build-client-fixed ~/standaloneViewerBuild -u default 
  - ls
after_success:
  - ls /home/travis/standaloneViewerBuild
  - ls ~/standaloneViewerBuild
  - ls /home/travis
  - ls /home/travis/build
  - ls /home/travis/build/OsiriX-Foundation/StandaloneViewer
  - chmod +x docker/deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: docker/deploy.sh 
  on:
    all_branches: true

