language: node_js

node_js:
  - "lts/*"

services:
  - docker

notifications:
  email: false

before_script:
  - export PATH=$HOME/.meteor:$PATH

before_script:
  - export METEOR_PACKAGE_DIRS="../../Packages"
  - cd StandaloneViewer
  - mkdir buildDirectory
  - cd StandaloneViewer
  - npm install -g meteor-build-client-fixed@0.4.3
  - meteor-build-client-fixed --version
  #- curl https://install.meteor.com | /bin/sh
  #- meteor npm install
script:
  - export BUILD_DIR=$TRAVIS_BUILD_DIR/build
  #- meteor-build-client-fixed $BUILD_DIR -u default
  #- cp -r $BUILD_DIR $TRAVIS_BUILD_DIR/docker/standaloneViewerBuild
  #- cp -r $BUILD_DIR $TRAVIS_BUILD_DIR/docker/ssl/standaloneViewerBuild
  - cp -r $TRAVIS_BUILD_DIR/KheopsDocker/appCompiled $TRAVIS_BUILD_DIR/docker/standaloneViewerBuild
  - cp -r $TRAVIS_BUILD_DIR/KheopsDocker/appCompiled $TRAVIS_BUILD_DIR/docker/tls/standaloneViewerBuild
  - ls $TRAVIS_BUILD_DIR/docker/standaloneViewerBuild
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x docker/deploy_none_tls.sh
  - chmod +x docker/tls/deploy_tls.sh
deploy:
  skip_cleanup: true
  provider: script
  script: 
    ./docker/deploy_none_tls.sh;
    ./docker/tls/deploy_tls.sh 
  on:
    all_branches: true


