language: node_js

node_js:
  - "lts/*"

services:
  - docker

notifications:
  email: false

before_script:
  - export PATH=$HOME/.meteor:$PATH

cache:
  directories:
    - ~/.meteor
    - node_modules
    - OHIFViewer/node_modules

jobs:
  include:

    - stage: build standalone viewer
      before_script:
        - export ROOT_URL=default
        - export METEOR_PACKAGE_DIRS="../../Packages"
        - cd StandaloneViewer
        - mkdir buildDirectory
        - cd StandaloneViewer
        - npm install -g meteor-build-client-fixed@0.4.3
        - meteor-build-client-fixed --version
        - curl https://install.meteor.com | /bin/sh
        - meteor npm install
      script:
        - meteor-build-client-fixed ~/standaloneViewerBuild -u $ROOT_URL
      after_success:
        - ls ~/standaloneViewerBuild
        - ls /home/travis
        - ls /home/travis/build
        - ls /home/travis/build/Viewers/StandaloneViewer
      #deploy:
      #  provider: s3
      #  access_key_id: $AWS_ACCESS_KEY_ID
      #  secret_access_key: $AWS_SECRET_ACCESS_KEY
      #  bucket: ohif-viewer
      #  region: eu-central-1
      #  skip_cleanup: true
      #  local_dir: /home/travis/standaloneViewerBuild
      #  acl: public_read
      #  on:
      #    branch: master
