language: node_js

node_js:
  - "lts/*"

services:
  - docker

notifications:
  email: false

before_script:
  - export PATH=$HOME/.meteor:$PATH

before_script:
  - export METEOR_PACKAGE_DIRS="../../Packages"
  - cd StandaloneViewer
  - mkdir buildDirectory
  - cd StandaloneViewer
  - npm install -g meteor-build-client-fixed@0.4.3
  - meteor-build-client-fixed --version
  - curl https://install.meteor.com | /bin/sh
  - meteor npm install
script:
  - meteor-build-client-fixed $TRAVIS_BUILD_DIR/docker/standaloneViewerBuild -u default
  #- mv $TRAVIS_BUILD_DIR/KheopsDocker/appCompiled $TRAVIS_BUILD_DIR/docker/standaloneViewerBuild
  - ls $TRAVIS_BUILD_DIR/docker/standaloneViewerBuild
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x docker/deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: docker/deploy.sh 
  on:
    all_branches: true
